name: Update Traffic

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download traffic feed
        run: |
          curl -s https://api.rwsverkeersinfo.nl/api/traffic/ > rws.json

      - name: Create traffic.json
        run: |
          python3 - <<'EOF'
          import json

          with open("rws.json", "r", encoding="utf-8") as f:
              data = json.load(f)

          result = {
              "A7": [],
              "N33": []
          }

          for item in data.get("obstructions", []):

              record = {
                  "titel": item.get("title", ""),
                  "locatie": item.get("locationText", "")
              }

              road = item.get("roadNumber", "")

              if road == "A7":
                  result
